tap "1password/tap", trusted: true
tap "aquaproj/aqua", trusted: true
tap "arl/arl", trusted: true
tap "hashicorp/tap", trusted: true
tap "homebrew/bundle", trusted: true
tap "homebrew/services", trusted: true
tap "int128/ghcp", trusted: true
tap "tilt-dev/tap", trusted: true
brew "anyenv", trusted: true
brew "aqua", trusted: true
brew "bash", trusted: true
brew "brush", trusted: true
brew "cmake", trusted: true
brew "colima", trusted: true
brew "coreutils", trusted: true
brew "direnv", trusted: true
brew "docker", link: false
brew "duckdb", trusted: true
brew "fd", trusted: true
brew "unixodbc", trusted: true
brew "freetds", trusted: true
brew "fzf", trusted: true
brew "gh", trusted: true
brew "git", trusted: true
brew "go", trusted: true
brew "gomplate", trusted: true
brew "gopls", trusted: true
brew "grep", trusted: true
brew "helm", trusted: true
brew "helmfile", trusted: true
brew "jq", trusted: true
brew "k9s", trusted: true
brew "kind", trusted: true
brew "kustomize", trusted: true
brew "lazydocker", trusted: true
brew "libpg_query", trusted: true
brew "libpq", trusted: true
brew "zstd", trusted: true
brew "markdown-oxide", trusted: true
brew "mycli", trusted: true
brew "zlib", trusted: true
brew "mysql-client", trusted: true
brew "mysql-client@8.0", trusted: true
brew "tree-sitter", trusted: true
brew "neovim", trusted: true
brew "parallel", trusted: true
brew "peco", trusted: true
brew "pinact", trusted: true
brew "pipx", trusted: true
brew "pkgconf", trusted: true
brew "pnpm", trusted: true
brew "poppler", trusted: true
brew "postgresql@14", trusted: true
brew "qemu", trusted: true
brew "reattach-to-user-namespace", trusted: true
brew "ripgrep", trusted: true
brew "saml2aws", trusted: true
brew "stern", trusted: true
brew "terraform-docs", trusted: true
brew "tflint", trusted: true
brew "tfmigrate", trusted: true
brew "tfsec", trusted: true
brew "the_silver_searcher", trusted: true
brew "tig", trusted: true
brew "tilt", trusted: true
brew "tmux", trusted: true
brew "tree", trusted: true
brew "trivy", trusted: true
brew "typos-cli", trusted: true
brew "uv", trusted: true
brew "vegeta", trusted: true
brew "yazi", args: ["HEAD"], trusted: true
brew "yq", trusted: true
brew "z", trusted: true
brew "zoxide", trusted: true
brew "zsh-autocomplete", trusted: true
cask "1password-cli", trusted: true
cask "claude-code", trusted: true
cask "fleet", trusted: true
cask "font-fira-code", trusted: true
cask "font-go-mono-nerd-font", trusted: true
cask "font-hackgen", trusted: true
cask "font-hackgen-nerd", trusted: true
cask "font-jetbrains-mono-nerd-font", trusted: true
cask "hyper", trusted: true
cask "wezterm@nightly", trusted: true
npm "corepack"
cask "claude"
