apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mines.myfirstcontroller.mshr.doc
spec:
  group: myfirstcontroller.mshr.doc
  names:
    kind: Mine
    plural: mines
    singular: mine
    shortNames:
      - mine
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                jobName:
                  type: string
                image:
                  type: string
                replicas:
                  type: integer
                  minimum: 1
                  maximum: 10
            status:
              type: object
              properties:
                availableReplicas:
                  type: integer
      additionalPrinterColumns:
        - jsonPath: .spec.jobName
          name: jobName
          type: string
        - jsonPath: .spec.image
          name: image
          type: string
        - jsonPath: .spec.replicas
          name: replicas
          type: integer
        - jsonPath: .metadata.creationTimestamp
          name: AGE
          type: date
      subresources:
        scale:
          specReplicasPath: .spec.replicas
          statusReplicasPath: .status.replicas
          labelSelectorPath: .status.labelSelector
