apiVersion: batch/v1
kind: Job
metadata:
  name: hello-job
spec:
  completions: 1
  backoffLimit: 1
  template:
    spec:
      containers:
        - name: hello-job
          image: hello-job:latest
      restartPolicy: Never
