apiVersion: v1
kind: ServiceAccount
metadata:
  name: mine
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mine
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["*"]
  - apiGroups: ["mines.myfirstcontroller.mshr.doc"]
    resources: ["mines"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mine
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  kind: Role
  name: mine
  apiGroup: rbac.authorization.k8s.io
