apiVersion: ctlptl.dev/v1alpha1
kind: Registry
name: hello-registry
port: 5000
---
apiVersion: ctlptl.dev/v1alpha1
kind: Cluster
name: kind-hello
product: kind
kubernetesVersion: v1.22.0
registry: hello-registry
