apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: samples.stable.example.com
spec:
  group: stable.example.com
  names:
    kind: Sample
    plural: samples
    singular: sample
    shortNames:
      - sp
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                message:
                  type: string
                image:
                  type: string
                replicas:
                  type: integer
                  default: 1
              required:
                - message
      additionalPrinterColumns:
        - jsonPath: .spec.message
          name: message
          type: string
        - jsonPath: .metadata.creationTimestamp
          name: AGE
          type: date
      subresources:
        scale:
          specReplicasPath: .spec.replicas
          statusReplicasPath: .status.replicas
          labelSelectorPath: .status.labelSelector
