apiVersion: apps/v1
kind: Deployment
metadata:
  name: myfirstcontroller
  labels:
    app: myfirstcontroller
spec:
  replicas: 1
  template:
    metadata:
      name: myfirstcontroller
      labels:
        app: myfirstcontroller
    spec:
      containers:
        - name: myfirstcontroller
          image: myfirstcontroller:latest
          imagePullPolicy: Never
      restartPolicy: Always
  selector:
    matchLabels:
      app: myfirstcontroller
